[tool.aerich]
tortoise_orm = "app.db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.isort]
atomic = true
case_sensitive = true
float_to_top = true
force_single_line = true
line_length = 80
lines_after_imports = 2
known_first_party = ["app"]
profile = "black"
remove_redundant_aliases = true
src_paths = "src"

[tool.pytest.ini_options]
addopts = ["-rsxX", "--color=yes", "--strict-markers"]
filterwarnings = ["error", "ignore::DeprecationWarning"]
looponfailroots = ["app", "db", "migrations", "tests"]
minversion = "7.0"
testpaths = "tests"
xfail_strict = true
